apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-evaluator-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${STORAGE_CLASS_NAME}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-evaluator-examples-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${STORAGE_CLASS_NAME}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-evaluator-results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${STORAGE_CLASS_NAME}
