- section: "Data Scope and Feature Engineering"
  prompt: |
    Describe the data sources and scope for the AI component.

- section: "2.1. Data Sources and Collection"
  prompt: |
    Describe the data sources used for developing the AI component:
    - What are the key data sources?
    - How are they collected and preprocessed?
    - What is the time period covered by the data?
    - What is the data refresh frequency?

- section: "2.2. Feature Engineering and Selection"
  prompt: |
    Explain the feature engineering process:
    - What are the key features used in the model?
    - How were features engineered and selected?
    - What techniques were used for feature selection?
    - How were features validated for relevance?

- section: "2.3. Data Quality Checks"
  prompt: |
    Detail the data quality processes:
    - What data quality checks are performed?
    - How are missing values handled?
    - What outlier detection methods are used?
    - How are data distributions monitored?
